export const CHANGE_PLAYING_SONG = 'player/CHANGE_PLAYING_SONG'
export const CHANGE_PLAY_LIST = 'player/CHANGE_PLAY_LIST'
export const CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX'
